# Generated by Django 3.1.1 on 2020-10-02 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 2, 13, 9, 15, 517284, tzinfo=utc)),
        ),
    ]
